### ISSUE TITLE
Background image in fullscreen is the default WhatsApp one

### ISSUE THREAD

**Issue by ransagy** [tncga/whats-up-darkness#1]
I opened the 1.0 alpha release, logged in via the QR scan.
When the window isn't full screen/maximized, The background doesn't show (WhatsApp's behavior of course) and everything is darkened.
When maximized you can see the default white-green background. Can this be darkened as well?

**Comment by gokberkakdeniz** [comment]
Hi, It was caused by electron's "BrowserWindow.webContents.insertCSS" function. I injected CSS manually via "BrowserWindow.webContents.executeJavaScript" in new version. But I did not add the new release because singleInstance function does not work on Windows thereby unknown reasons. I will suspend this feature and release the new version.

**Comment by ransagy** [comment]
Confirmed, works fine here in the new release.
