### ISSUE TITLE
"WhatsApp works with Google Chrome 36+" when i try to open it in the taskbar

### ISSUE THREAD

**Issue by Maxcension** [tncga/whats-up-darkness#2]
when i try to open the app in the taskbar (pinned app), i have this error.
i don't why, and if i total close the app, it works when i reopen it.
althrough, thanks for this app, i reaaaaally love it!

![2019-04-20 12_28_05-Window](https://user-images.githubusercontent.com/10364593/56864915-6c212d00-69c8-11e9-8b0f-813bd19c432f.png)
![2019-04-28 15_12_35-Window](https://user-images.githubusercontent.com/10364593/56864916-6c212d00-69c8-11e9-8623-64fe2a568a1d.png)
![2019-04-28 15_12_50-](https://user-images.githubusercontent.com/10364593/56864917-6c212d00-69c8-11e9-9b92-fa612bc1f69f.png)

**Comment by Maxcension** [comment]
i will try to build the app by myself instead of use the release 2.0.4 bc i saw you made a commit 12 days ago to fix this!

**Comment by gokberkakdeniz** [comment]
When this issue was occurred again, I was rewriting some parts of this app. Because of that, I did not release the new version, although i fixed it. And some Linux (actually GNOME DE) related issues delayed new version. After the tests, if there is no problem, I will publish the new version (probably today).
